apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
      - name: todo-service
        image: todoaksacr.azurecr.io/todo-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          # Replace <postgres_fqdn> with the FQDN provided by the PostgreSQL resource
          value: "postgresql://dbadmin%40todo-postgres:YourSecurePassword123!@todo-postgres.postgres.database.azure.com:5432/tododb?sslmode=require"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          # Direct telemetry to the OpenTelemetry collector service deployed below
          value: "http://otel-collector:4317"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"