apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp
    port: 4317
    targetPort: 4317
  - name: grafana
    port: 3000
    targetPort: 3000
  type: LoadBalancer