apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: test.example.com  # Replace with your domain or use a placeholder like localhost if using /etc/hosts for testing
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-service
            port:
              number: 80