name: Deploy to AKS

on:
  push:
    branches:
      - feat/add-infrastructure
  workflow_dispatch: # <-- Allows manual trigger

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: "todo-aks-rg"
      AKS_CLUSTER: "todo-aks-cluster"
      ACR_NAME: "todoaksacr"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        run: |
          az login --service-principal \
            --username ${{ secrets.ARM_CLIENT_ID }} \
            --password ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }}

      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Provision Infrastructure with Terraform
        working-directory: infrastructure/terraform
        env:
          TF_VAR_client_id: ${{ secrets.TF_VAR_client_id }}
          TF_VAR_client_secret: ${{ secrets.TF_VAR_client_secret }}
          TF_VAR_subscription_id: ${{ secrets.TF_VAR_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.TF_VAR_tenant_id }}
          TF_VAR_location: ${{ secrets.TF_VAR_location }}
        run: |
          terraform init
          terraform plan -out=tfplan
          # terraform apply -auto-approve tfplan

  deploy-app:
    needs: terraform-deploy
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      # Manual step for `terraform apply`
      # - name: Terraform Apply
      #   working-directory: infrastructure/terraform
      #   run: terraform apply -auto-approve

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR using Azure CLI
        run: |
          az acr login --name $ACR_NAME

      - name: Build and Push Image with Docker Compose
        run: |
          docker compose build
          docker compose push
      
      - name: Deploy Traefik Ingress Controller via Helm
        run: |
          helm repo add traefik https://traefik.github.io/helm-charts
          helm repo update
          helm install traefik traefik/traefik --namespace traefik --create-namespace

      - name: Deploy Application to AKS using kubectl
        working-directory: infrastructure/terraform
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f todo-service.yaml
          kubectl apply -f todo-ingress.yaml
          kubectl apply -f otel-collector.yaml
          kubectl apply -f otel-service.yaml
          
      - name: Check Rollout Status
        run: |
          kubectl rollout status deployment/todo-service