name: Deploy to AKS

on:
  push:
    branches:
      - feat/add-infrastructure

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: "todo-aks-rg"
      AKS_CLUSTER: "todo-aks-cluster"
      ACR_NAME: "todoaksacr"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/cli@v1
        with:
          azcliversion: '2.42.0'

      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Provision Infrastructure with Terraform
        working-directory: infrastructure/terraform
        run: |
          terraform init
          terraform plan -out=tfplan
          # terraform apply -auto-approve tfplan

      # Exit early step (successful exit)
      - name: Exit early after Terraform Plan
        if: success()
        run: |
          echo "Exiting early after Terraform plan"
          exit 0

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER --overwrite-existing

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR using Azure CLI
        run: |
          az acr login --name $ACR_NAME

      - name: Build and Push Image with Docker Compose
        run: |
          docker compose build
          docker compose push
      
      - name: Deploy Traefik Ingress Controller via Helm
        run: |
          helm repo add traefik https://traefik.github.io/helm-charts
          helm repo update
          helm install traefik traefik/traefik --namespace traefik --create-namespace

      - name: Deploy Application to AKS using kubectl
        working-directory: infrastructure/terraform
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f todo-service.yaml
          kubectl apply -f todo-ingress.yaml
          kubectl apply -f otel-collector.yaml
          kubectl apply -f otel-service.yaml
          
      - name: Check Rollout Status
        run: |
          kubectl rollout status deployment/todo-service